data(vth)
data(hipp)
testthat::expect_that(vth, testthat::is_a("character"))
testthat::expect_that(hipp, testthat::is_a("character"))
testthat::expect_that(brainrange(0,10), testthat::is_a("numeric"))
